import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const StyledDiv = styled.div`
  margin-top: 3rem;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TVNZ</title>
        <meta name="description" content="Generated by TVNZ" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">TVNZ!</a>
        </h1>
        <StyledDiv>Fwfwfw</StyledDiv>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.tvnz.co.nz" target="_blank">
          Powered by TVNZ
        </a>
      </footer>
    </div>
  );
}
